apiVersion: apps/v1
kind: Deployment
metadata:
  name: isaac-playlists-recommender-ml
  namespace: isaac
  labels:
    app.kubernetes.io/instance: playlist-recommender 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: isaac-playlists-recommender-ml
  template:
    metadata:
      labels:
        app: isaac-playlists-recommender-ml
      annotations:
        checksum/config: "{{ .Files.Get `config.yaml` | sha256sum }}"  # Forces redeployment on dataset change
    spec:
      containers:
      - name: playlists-recommender-ml
        image: kemurukagami/playlists-recommender-system-ml:0.5
        env:
        - name: DATASET_FILE
          valueFrom:
            configMapKeyRef:
              name: playlist-dataset-config
              key: dataset
        volumeMounts:
        - name: shared-storage
          mountPath: /app/shared
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: project2-pv-isaac
