apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-recommender-ml
  namespace: isaac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playlist-recommender-ml
  template:
    metadata:
      labels:
        app: playlist-recommender-ml
    spec:
      containers:
      - name: playlist-recommender-ml
        image: kemurukagami/playlists-recommender-system-ml:0.1
        volumeMounts:
        - name: dataset-volume
          mountPath: /data
        - name: shared-storage
          mountPath: /shared
      volumes:
      - name: dataset-volume
        persistentVolumeClaim:
          claimName: project2-pv-isaac
      - name: shared-storage
        persistentVolumeClaim:
          claimName: project2-pv-isaac
