apiVersion: apps/v1
kind: Deployment
metadata:
  name: isaac-playlists-recommender-frontend
  namespace: isaac
spec:
  replicas: 2
  selector:
    matchLabels:
      app: isaac-playlists-recommender-frontend
  template:
    metadata:
      labels:
        app: isaac-playlists-recommender-frontend
    spec:
      containers:
      - name: playlists-recommender-frontend
        image: kemurukagami/playlists-recommender-system-frontend:0.4
        ports:
        - containerPort: 52008
        volumeMounts:
        - name: shared-storage
          mountPath: /app/shared
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: project2-pv-isaac
