apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-recommender-frontend
  namespace: isaac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playlist-recommender-frontend
  template:
    metadata:
      labels:
        app: playlist-recommender-frontend
    spec:
      containers:
      - name: playlist-recommender-frontend
        image: kemurukagami/playlists-recommender-system-frontend:0.2
        ports:
        - containerPort: 52008
        volumeMounts:
        - name: shared-storage
          mountPath: /shared
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: project2-pv-isaac
