apiVersion: v1
kind: Service
metadata:
  name: playlist-recommender-service
spec:
  selector:
    app: isaac-playlist-recommender  # Must match the label in your deployment.yaml
  ports:
    - protocol: TCP
      port: 52008  # Port for accessing the service
      targetPort: 52008  # Port where your Flask app is listening inside the container
  type: LoadBalancer  # You can change this to ClusterIP if you only need internal access
