apiVersion: v1
kind: Service
metadata:
  name: isaac-playlist-recommender-service
  namespace: isaac
spec:
  type: LoadBalancer
  selector:
    app: isaac-playlist-recommender
  ports:
    - protocol: TCP
      port: 80
      targetPort: 52008
