apiVersion: v1
kind: Service
metadata:
  name: isaac-playlists-recommender-service
  namespace: isaac
spec:
  type: NodePort
  selector:
    app: isaac-playlists-recommender-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 52008
      nodePort: 52008
