apiVersion: v1
kind: Service
metadata:
  name: playlist-recommender-service
  namespace: isaac
spec:
  type: LoadBalancer
  selector:
    app: playlist-recommender-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 52008
